name: Blog CI/CD

# 触发条件：在 push 到 myblog 分支后触发
on: 
  #push
  workflow_dispatch: # 手动触发

#env:
#  TZ: Asia/Shanghai

jobs:
  time-judge:
    name: gitnew
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Compare GitCommitIimeGithub And GitCommitIimeGitee
      env: 
        # Github 仓库
        GITHUB_REPO: github.com/SkySkin-w/blog-devlop
        # Coding 仓库
        #CODING_REPO: e.coding.net/yifanzheng/blogs.git
        # Gitee 仓库
        #GITEE_REPO: gitee.com/skyskin-w/blog-devlop
      run: |
        #创建临时文件拉取gitee
        echo '创建临时文件拉取gitee'
        mkdir tempCloneDir
        cd ./tempCloneDir/
        pwd
        #git clone  https://gitee.com/skyskin-w/Test.git #gitee仓库地址
        git clone -b myblog https://gitee.com/skyskin-w/skyskin-w.gitee.io.git
        cd ./skyskin-w.gitee.io/

        rm -rf ./.git

        git init 

        git add .
        git config user.name "zeyue"
        git config user.email "735600779@qq.com"
        git commit -m "GitHub Actions Auto Builder at $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "https://${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" master:master


